const countries = [
  {
    id: 1,
    name: "Canada",
    country_code: "CA",
    capital: "Ottawa",
    flag: "https://flagcdn.com/w80/ca.png",
    population: 38.01,
  },
  {
    id: 2,
    name: "France",
    country_code: "FR",
    capital: "Paris",
    flag: "https://flagcdn.com/w80/fr.png",
    population: 67.3,
  },
  {
    id: 3,
    name: "Argentina",
    country_code: "AR",
    capital: "Buenos Aries",
    flag: "https://flagcdn.com/w80/ar.png",
    population: 45.38,
  },
  {
    id: 4,
    name: "United States of America",
    country_code: "USA",
    capital: "Washington",
    flag: "https://flagcdn.com/w80/us.png",
    population: 329.5,
  },
  {
    id: 5,
    name: "Italy",
    country_code: "IT",
    capital: "Rome",
    flag: "https://flagcdn.com/w80/it.png",
    population: 59.55,
  },
  {
    id: 6,
    name: "Japan",
    country_code: "JP",
    capital: "Tokyo",
    flag: "https://flagcdn.com/w80/jp.png",
    population: 125.8,
  },
  {
    id: 7,
    name: "Nigeria",
    country_code: "NG",
    capital: "Lagos",
    flag: "https://flagcdn.com/w80/ng.png",
    population: 206.1,
  },
];
export { countries };
